home:
    pattern:  /
    defaults: { _controller: CCETCDirectoryBundle:Pages:static, template: CCETCDirectoryBundle:Pages:home.html.twig }
    
about:
    pattern:  /about
    defaults: { _controller: CCETCDirectoryBundle:Pages:static, template: CCETCDirectoryBundle:Pages:about.html.twig }
    
listings:
    pattern:  /listings
    defaults: { _controller: CCETCDirectoryBundle:Directory:listings }

generateLocations:
    pattern:  /listings/generate-locations
    defaults: { _controller: CCETCDirectoryBundle:Directory:generateLocations }

profile:
    pattern:  /listings/{id}
    defaults: { _controller: CCETCDirectoryBundle:Directory:profile, id: id }
    
signup:
    pattern:  /signup
    defaults: { _controller: CCETCDirectoryBundle:Directory:signup }