home:
    pattern:  /
    defaults: { _controller: CCETCDirectoryBundle:Pages:static, template: CCETCDirectoryBundle:Pages:home.html.twig }
    
about:
    pattern:  /about
    defaults: { _controller: CCETCDirectoryBundle:Pages:static, template: CCETCDirectoryBundle:Pages:about.html.twig }

CCETDirectoryBundle_Listing:
    resource: .
    type: listing